Models/Compra.cs
using System.ComponentModel.DataAnnotations;

namespace Precificacao.Models
{
    public class Compra
    {
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "Id do ingrediente")]
        public int IngredienteId { get; set; }

        [Display(Name = "Nome do ingrediente")]
        public string? IngredienteNome { get; set; }

        [Display(Name = "Quantidade")]
        public decimal Quantidade { get; set; }

        [Display(Name = "Preço")]
        public decimal Preco { get; set; }

        [Display(Name = "Data da compra")]
        public DateTime Data { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Precificacao.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Ingrediente.cs
using System.ComponentModel.DataAnnotations;

namespace Precificacao.Models;
public class Ingrediente
{
    [Display(Name = "Código")]
    public int Id { get; set; }

    [Display(Name = "Nome")]
    public string? Nome { get; set; }

    [Display(Name = "Unidade de medida")]
    public string? UnidadeMedida { get; set; }

    [Display(Name = "Quantidade em estoque")]
    public decimal QuantidadeEstoque { get; set; }
}

Controllers/CompraController.cs
using Microsoft.AspNetCore.Mvc;
using Precificacao.Models;
using Precificacao.Repositories;

public class CompraController : Controller
{
    private readonly IRepository<Compra> _compraRepository;
    private readonly IIngredienteRepository _ingredienteRepository;

    public CompraController(
        IRepository<Compra> compraRepository,
        IIngredienteRepository ingredienteRepository
    )
    {

        _compraRepository = compraRepository;
        _ingredienteRepository = ingredienteRepository;
    }

    public async Task<IActionResult> Index()
    {
        var compras = await _compraRepository.GetAll();
        foreach (var compra in compras)
        {
            var ingrediente = await _ingredienteRepository.GetById(compra.IngredienteId);
            if (ingrediente == null)
            {
                return NotFound();
            }
            compra.IngredienteNome = ingrediente.Nome;
        }
        return View(compras);
    }

    public async Task<IActionResult> Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Compra compra)
    {
        if (ModelState.IsValid)
        {
            var ingrediente = await _ingredienteRepository.GetById(compra.IngredienteId);
            if (ingrediente == null)
            {
                return NotFound();
            }

            await _compraRepository.Add(compra);
            await _ingredienteRepository.UpdateQuantidade(ingrediente, compra.Quantidade);
            return RedirectToAction(nameof(Index));
        }
        return View(compra);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var compra = await _compraRepository.GetById(id);
        if (compra == null)
        {
            return NotFound();
        }
        return View(compra);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, Compra compra)
    {
        if (id != compra.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                await _compraRepository.Update(compra);
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
        return View(compra);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var compra = await _compraRepository.GetById(id);
        if (compra == null)
        {
            return NotFound();
        }

        var ingrediente = await _ingredienteRepository.GetById(compra.IngredienteId);
        if (ingrediente == null)
        {
            return NotFound();
        }
        compra.IngredienteNome = ingrediente.Nome;

        return View(compra);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _compraRepository.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/IngredienteController.cs
using Microsoft.AspNetCore.Mvc;
using Precificacao.Models;
using Precificacao.Repositories;

public class IngredienteController : Controller
{
    private readonly IIngredienteRepository _ingredienteRepository;

    public IngredienteController(IIngredienteRepository ingredienteRepository)
    {
        _ingredienteRepository = ingredienteRepository;
    }

    public async Task<IActionResult> Index()
    {
        var ingredientes = await _ingredienteRepository.GetAll();
        return View(ingredientes);
    }

    public async Task<IActionResult> Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Ingrediente ingrediente)
    {
        if (ModelState.IsValid)
        {
            await _ingredienteRepository.Add(ingrediente);
            return RedirectToAction(nameof(Index));
        }
        return View(ingrediente);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var ingrediente = await _ingredienteRepository.GetById(id);
        if (ingrediente == null)
        {
            return NotFound();
        }
        return View(ingrediente);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, Ingrediente ingrediente)
    {
        if (id != ingrediente.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                await _ingredienteRepository.Update(ingrediente);
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
        return View(ingrediente);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var ingrediente = await _ingredienteRepository.GetById(id);
        if (ingrediente == null)
        {
            return NotFound();
        }
        return View(ingrediente);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _ingredienteRepository.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Views/Compra/Create.cshtml
@model Compra
@{
    ViewData["Title"] = "Incluir Compra";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="IngredienteId" class="control-label"></label>
        <input asp-for="IngredienteId" class="form-control" />
        <span asp-validation-for="IngredienteId" class="text-danger"></span>
    </div>
    <br/>
    <div class="form-group">
        <label asp-for="Quantidade" class="control-label"></label>
        <input asp-for="Quantidade" class="form-control" />
        <span asp-validation-for="Quantidade" class="text-danger"></span>
    </div>
    <br/>
    <div class="form-group">
        <label asp-for="Preco" class="control-label"></label>
        <input asp-for="Preco" class="form-control" />
        <span asp-validation-for="Preco" class="text-danger"></span>
    </div>
    <br/>
    <div class="form-group">
        <label asp-for="Data" class="control-label"></label>
        <input asp-for="Data" class="form-control" />
        <span asp-validation-for="Data" class="text-danger"></span>
    </div>
    <br/><br/>
    <button type="submit" class="btn btn-primary">Salvar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

Views/Compra/Delete.cshtml
@model Compra

@{
    ViewData["Title"] = "Excluir Compra";
}

<h2>@ViewData["Title"]</h2>
<br/>
<h3>Tem certeza que deseja excluir esta compra?</h3>
<br/><br/>
<div>
    <h4>Compra</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IngredienteId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IngredienteId)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IngredienteNome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IngredienteNome)
        </dd>
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
    </dl>
    <br/><br/>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">Excluir</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

Views/Compra/Edit.cshtml
@model Compra

@{
    ViewData["Title"] = "Editar Compra";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit">
    <div class="form-group">
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="IngredienteId" class="control-label"></label>
            <input asp-for="IngredienteId" class="form-control" />
            <span asp-validation-for="IngredienteId" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="Quantidade" class="control-label"></label>
            <input asp-for="Quantidade" class="form-control" />
            <span asp-validation-for="Quantidade" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="Preco" class="control-label"></label>
            <input asp-for="Preco" class="form-control" />
            <span asp-validation-for="Preco" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="Data" class="control-label"></label>
            <input asp-for="Data" class="form-control" />
            <span asp-validation-for="Data" class="text-danger"></span>
        </div>
        <br /><br />
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Compra/Index.cshtml
@model IEnumerable<Compra>

@{
    ViewData["Title"] = "Lista de Compras";
}

<h1>@ViewData["Title"]</h1>
<br />
<p>
    <a asp-action="Create" class="btn btn-primary">Adicionar nova compra</a>
</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().IngredienteId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().IngredienteNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Quantidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Data)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var compra in Model)

        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => compra.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => compra.IngredienteId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => compra.IngredienteNome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => compra.Quantidade)
                </td>
                <td>
                    R$@Html.DisplayFor(modelItem => compra.Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => compra.Data)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@compra.Id" class="btn btn-warning">Editar</a>
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@compra.Id" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Ingrediente/Create.cshtml
@model Ingrediente
@{
    ViewData["Title"] = "Incluir Ingrediente";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Nome" class="control-label"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <br/>
    <div class="form-group">
        <label asp-for="UnidadeMedida" class="control-label"></label>
        <input asp-for="UnidadeMedida" class="form-control" />
        <span asp-validation-for="UnidadeMedida" class="text-danger"></span>
    </div>
    <br/><br/>
    <button type="submit" class="btn btn-primary">Salvar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

Views/Ingrediente/Delete.cshtml
@model Ingrediente

@{
    ViewData["Title"] = "Excluir Ingrediente";
}

<h2>@ViewData["Title"]</h2>
<br/>
<h3>Tem certeza que deseja excluir este ingrediente?</h3>
<br/><br/>
<div>
    <h4>Ingrediente</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UnidadeMedida)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UnidadeMedida)
        </dd>

    </dl>
    <br/><br/>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">Excluir</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

Views/Ingrediente/Edit.cshtml
@model Ingrediente

@{
    ViewData["Title"] = "Editar Ingrediente";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit">
    <div class="form-group">
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <label asp-for="UnidadeMedida" class="control-label"></label>
            <input asp-for="UnidadeMedida" class="form-control" />
            <span asp-validation-for="UnidadeMedida" class="text-danger"></span>
        </div>
        <br/><br/>
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ingrediente/Index.cshtml
@model IEnumerable<Ingrediente>

@{
    ViewData["Title"] = "Lista de Ingredientes";
}

<h1>@ViewData["Title"]</h1>
<br/>
<p>
    <a asp-action="Create" class="btn btn-primary">Adicionar novo ingrediente</a>
</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().UnidadeMedida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().QuantidadeEstoque)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ingrediente in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => ingrediente.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => ingrediente.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => ingrediente.UnidadeMedida)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => ingrediente.QuantidadeEstoque)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@ingrediente.Id" class="btn btn-warning">Editar</a> 
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@ingrediente.Id" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Precificacao</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Precificacao.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Precificação de receitas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingrediente" asp-action="Index">Ingredientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="Index">Compras</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Precificação de receitas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>